name: Preview Deployment

on:
  pull_request:
    branches: [main, develop]
  push:
    branches-ignore: [main]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  preview:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_ENV: preview
          NEXT_PUBLIC_SITE_URL: ${{ vars.PREVIEW_URL }}

      - name: Deploy Preview to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: apps/generator-app/.next
          production-deploy: false
          alias: preview-${{ github.event.number || github.sha }}
          netlify-config-path: infrastructure/netlify/dev.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready!\n\nURL: https://preview-${context.issue.number}--${process.env.NETLIFY_SITE_ID}.netlify.app`
            })
