import fs from 'fs'
import path from 'path'
import { NICHE_META, NICHE_SLUGS, getNicheSlugs } from './niche-meta'
// Generated by scripts/build-template-manifest.mjs during prebuild. Holds
// all template metadata (slug, name, fields, pages, snippet, relative dir)
// so the runtime SSR functions never have to walk the 302 MB template
// directory — that directory is excluded from the function bundle via
// next.config.js outputFileTracingExcludes and served from the CDN.
// The committed file is a `{}` stub overwritten at build time.
import MANIFEST_JSON from './manifest.generated.json'

export { NICHE_META, NICHE_SLUGS, getNicheSlugs }

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

export interface TemplateField {
  name: string
  label: string
  type: string
  required?: boolean
  default?: string
}

export interface TemplateMeta {
  slug: string
  name: string
  niche: string
  nicheSlug: string
  layoutFamily?: string
  voiceFamily?: string
  /** Gallery ordering key (lower = earlier). Undefined sorts last. */
  order?: number
  /** Featured on niche landing pages */
  featured?: boolean
  /** Showcase card order on niche landing (lower = earlier) */
  showcaseOrder?: number
  pages: string[]
  /**
   * Path to the template's directory, RELATIVE to the templates root
   * (e.g. `"aromatherapy/aromatherapy-2026-02-16T14-59-46-083Z-001"`).
   * The registry composes both filesystem paths and CDN URLs from this.
   */
  dir: string
  fields: TemplateField[]
  /** First 160 chars of visible text from index.html (for card preview) */
  snippet: string
}

export interface NicheInfo {
  slug: string
  label: string
  description: string
  icon: string
  accent: string
  templateCount: number
}

type ManifestShape = Record<string, TemplateMeta[]>

/* ------------------------------------------------------------------ */
/* Filesystem + URL roots                                              */
/* ------------------------------------------------------------------ */

/**
 * Candidate locations for templates on disk. We prefer the static
 * `public/_templates` copy so the same path works at build (SSG runs
 * `getNiches()` / `getFeaturedTemplatesForNiche()`) and at dev. Both the
 * app-dir cwd (next dev/build) and the monorepo-root cwd (Netlify, root
 * scripts) are covered. The legacy `platform-builder/` paths remain as a
 * last-resort fallback so older tooling keeps working.
 */
const FS_ROOT_CANDIDATES: string[] = [
  path.join(process.cwd(), 'public', '_templates'),
  path.join(process.cwd(), 'apps', 'generator-app', 'public', '_templates'),
  path.join(process.cwd(), '..', '..', 'platform-builder'),
  path.join(process.cwd(), 'platform-builder'),
]

let _fsRoot: string | null | undefined
function getFsRoot(): string | null {
  if (_fsRoot !== undefined) return _fsRoot
  for (const candidate of FS_ROOT_CANDIDATES) {
    try {
      if (fs.existsSync(candidate)) {
        _fsRoot = candidate
        return _fsRoot
      }
    } catch { /* ignore */ }
  }
  _fsRoot = null
  return null
}

/** Base URL used to fetch template assets at runtime when fs is not available. */
function templateBaseUrl(): string {
  return (
    process.env.NEXT_PUBLIC_BASE_URL ||
    process.env.URL ||
    process.env.DEPLOY_PRIME_URL ||
    process.env.DEPLOY_URL ||
    `http://localhost:${process.env.PORT || 3000}`
  )
}

/* ------------------------------------------------------------------ */
/* Legacy fs-walking helpers — only used when the build-time manifest  */
/* is empty (the committed stub) AND templates are on disk. This keeps */
/* dev/test workflows working without running prebuild first.          */
/* ------------------------------------------------------------------ */

function extractSnippet(htmlPath: string): string {
  try {
    const html = fs.readFileSync(htmlPath, 'utf-8')
    const text = html
      .replace(/<script[\s\S]*?<\/script>/gi, '')
      .replace(/<style[\s\S]*?<\/style>/gi, '')
      .replace(/<[^>]+>/g, ' ')
      .replace(/\{\{[^}]+\}\}/g, '')
      .replace(/\s+/g, ' ')
      .trim()
    return text.slice(0, 160)
  } catch {
    return ''
  }
}

function stripBraces(key: string): string {
  return key.replace(/^\{\{/, '').replace(/\}\}$/, '')
}

const TYPE_KEYWORDS = new Set([
  'string', 'text', 'textarea', 'email', 'tel', 'phone', 'url', 'number',
  'int', 'integer', 'boolean', 'bool', 'date', 'datetime', 'time', 'json', 'array', 'object',
])

function inferType(name: string): string {
  const n = name.toLowerCase()
  if (n.includes('email')) return 'email'
  if (n.includes('phone')) return 'tel'
  if (n.includes('url') || n.includes('link') || n.includes('website')) return 'url'
  return 'text'
}

function normalizeField(f: any): TemplateField {
  const rawKey = f.key || f.name || ''
  const name = stripBraces(rawKey)
  return {
    name,
    label: f.label || name.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
    type: f.type || inferType(name),
    required: f.required ?? true,
    default: f.default ?? f.placeholder ?? f.example ?? undefined,
  }
}

function fieldFromMapEntry(key: string, val: unknown): TemplateField {
  const name = stripBraces(key)
  if (val && typeof val === 'object' && !Array.isArray(val)) {
    return normalizeField({ key: name, ...(val as Record<string, unknown>) })
  }
  if (typeof val === 'string') {
    const lower = val.trim().toLowerCase()
    if (TYPE_KEYWORDS.has(lower)) {
      return normalizeField({ key: name, type: lower === 'string' ? inferType(name) : lower })
    }
    if (!val.startsWith('{{') && !val.startsWith('[')) {
      return normalizeField({ key: name, default: val })
    }
  }
  return normalizeField({ key: name })
}

function dedupeFields(fields: TemplateField[]): TemplateField[] {
  const seen = new Set<string>()
  const out: TemplateField[] = []
  for (const f of fields) {
    if (!f.name || seen.has(f.name)) continue
    seen.add(f.name)
    out.push(f)
  }
  return out
}

function fieldsFromPlaceholders(placeholders: string[]): TemplateField[] {
  return placeholders.map((p) => normalizeField({ key: stripBraces(p) }))
}

function fieldsFromHtml(htmlPath: string): TemplateField[] {
  try {
    const html = fs.readFileSync(htmlPath, 'utf-8')
    const tokens = new Set<string>()
    const re = /\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g
    let m: RegExpExecArray | null
    while ((m = re.exec(html)) !== null) tokens.add(m[1])
    return fieldsFromPlaceholders([...tokens])
  } catch {
    return []
  }
}

function parseFields(fieldsPath: string): TemplateField[] {
  try {
    const raw = JSON.parse(fs.readFileSync(fieldsPath, 'utf-8'))
    if (Array.isArray(raw)) return raw.map(normalizeField)
    if (raw.groups && Array.isArray(raw.groups)) {
      const all: TemplateField[] = []
      for (const group of raw.groups) {
        if (Array.isArray(group.fields)) all.push(...group.fields.map(normalizeField))
      }
      return all
    }
    if (Array.isArray(raw.fields)) return raw.fields.map(normalizeField)
    if (raw.fields && typeof raw.fields === 'object' && !Array.isArray(raw.fields)) {
      return Object.entries(raw.fields).map(([key, val]) => fieldFromMapEntry(key, val))
    }
    if (raw.placeholders && typeof raw.placeholders === 'object') {
      return Object.entries(raw.placeholders).map(([key, val]) => {
        const name = stripBraces(key)
        return {
          name,
          label: name.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
          type: name.toLowerCase().includes('email') ? 'email' : name.toLowerCase().includes('phone') ? 'tel' : 'text',
          required: Array.isArray(raw.required) ? raw.required.includes(key) : true,
          default: typeof val === 'string' && !val.startsWith('{{') ? val : undefined,
        }
      })
    }
    if (typeof raw === 'object' && (raw.BUSINESS_NAME !== undefined || raw.business_name !== undefined)) {
      return Object.entries(raw)
        .filter(([k]) => k !== 'notes')
        .map(([key, val]) => {
          const name = stripBraces(key)
          return {
            name,
            label: name.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
            type: name.toLowerCase().includes('email') ? 'email' : name.toLowerCase().includes('phone') ? 'tel' : 'text',
            required: true,
            default: typeof val === 'string' && !val.startsWith('[') && !val.startsWith('{{') ? val : undefined,
          }
        })
    }
    return []
  } catch {
    return []
  }
}

function parseTemplateMetaFromFs(templateDir: string, niche: string, relDir: string): TemplateMeta | null {
  const indexPath = path.join(templateDir, 'index.html')
  if (!fs.existsSync(indexPath)) return null

  const templateJsonPath = path.join(templateDir, 'template.json')
  const fieldsJsonPath = path.join(templateDir, 'fields.json')

  let meta: any = {}
  if (fs.existsSync(templateJsonPath)) {
    try {
      meta = JSON.parse(fs.readFileSync(templateJsonPath, 'utf-8'))
    } catch { /* ignore */ }
  }

  const slug = meta.slug || path.basename(templateDir)
  const pages = meta.pages || fs.readdirSync(templateDir).filter((f: string) => f.endsWith('.html'))

  let fields = fs.existsSync(fieldsJsonPath) ? parseFields(fieldsJsonPath) : []
  if (fields.length === 0 && Array.isArray(meta.placeholders)) {
    fields = fieldsFromPlaceholders(meta.placeholders as string[])
  }
  if (fields.length === 0) {
    fields = fieldsFromHtml(indexPath)
  }
  fields = dedupeFields(fields)

  return {
    slug,
    name: meta.name || slug.replace(/-/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
    niche,
    nicheSlug: niche,
    layoutFamily: meta.layoutFamily,
    voiceFamily: meta.voiceFamily,
    order: typeof meta.order === 'number' ? meta.order : undefined,
    featured: meta.featured === true,
    showcaseOrder: typeof meta.showcaseOrder === 'number' ? meta.showcaseOrder : undefined,
    pages,
    dir: relDir.split(path.sep).join('/'),
    fields,
    snippet: extractSnippet(indexPath),
  }
}

function buildCacheFromFs(fsRoot: string): Map<string, TemplateMeta[]> {
  const cache = new Map<string, TemplateMeta[]>()
  for (const nicheSlug of Object.keys(NICHE_META)) {
    const nicheDir = path.join(fsRoot, nicheSlug)
    if (!fs.existsSync(nicheDir)) continue
    const templates: TemplateMeta[] = []
    for (const entry of fs.readdirSync(nicheDir)) {
      const templateDir = path.join(nicheDir, entry)
      if (!fs.statSync(templateDir).isDirectory()) continue
      const t = parseTemplateMetaFromFs(templateDir, nicheSlug, path.join(nicheSlug, entry))
      if (t) templates.push(t)
    }
    templates.sort((a, b) => {
      const ao = typeof a.order === 'number' ? a.order : Number.POSITIVE_INFINITY
      const bo = typeof b.order === 'number' ? b.order : Number.POSITIVE_INFINITY
      if (ao !== bo) return ao - bo
      return a.name.localeCompare(b.name)
    })
    cache.set(nicheSlug, templates)
  }
  return cache
}

/* ------------------------------------------------------------------ */
/* Cache assembly: prefer the precomputed manifest, fall back to fs    */
/* ------------------------------------------------------------------ */

let _cache: Map<string, TemplateMeta[]> | null = null

function ensureCache(): Map<string, TemplateMeta[]> {
  if (_cache) return _cache

  const manifest = MANIFEST_JSON as ManifestShape
  const manifestNiches = Object.keys(manifest)
  const manifestHasTemplates = manifestNiches.some((n) => (manifest[n]?.length ?? 0) > 0)

  if (manifestHasTemplates) {
    _cache = new Map()
    for (const nicheSlug of Object.keys(NICHE_META)) {
      _cache.set(nicheSlug, (manifest[nicheSlug] || []) as TemplateMeta[])
    }
    return _cache
  }

  // Manifest is the committed `{}` stub (or otherwise empty). Fall back to
  // walking the filesystem so dev/test workflows still work without the
  // prebuild script having run.
  const fsRoot = getFsRoot()
  if (fsRoot) {
    _cache = buildCacheFromFs(fsRoot)
    return _cache
  }

  _cache = new Map()
  return _cache
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

/** Get all niches with their metadata and counts */
export function getNiches(): NicheInfo[] {
  const cache = ensureCache()
  return Object.entries(NICHE_META).map(([slug, meta]) => ({
    slug,
    ...meta,
    templateCount: cache.get(slug)?.length || 0,
  }))
}

/** Get all templates for a niche */
export function getTemplatesForNiche(nicheSlug: string): TemplateMeta[] {
  const cache = ensureCache()
  return cache.get(nicheSlug) || []
}

/** Featured templates for niche landing showcase, ordered by showcaseOrder */
export function getFeaturedTemplatesForNiche(nicheSlug: string): TemplateMeta[] {
  return getTemplatesForNiche(nicheSlug)
    .filter((t) => t.featured)
    .sort((a, b) => {
      const ao = typeof a.showcaseOrder === 'number' ? a.showcaseOrder : Number.POSITIVE_INFINITY
      const bo = typeof b.showcaseOrder === 'number' ? b.showcaseOrder : Number.POSITIVE_INFINITY
      return ao - bo
    })
}

/** Get a single template by niche + slug */
export function getTemplate(nicheSlug: string, templateSlug: string): TemplateMeta | null {
  const templates = getTemplatesForNiche(nicheSlug)
  return templates.find((t) => t.slug === templateSlug) || null
}

/* ------------------------------------------------------------------ */
/* Body-content reads — async because runtime functions can't see the  */
/* template directory and must fetch it from the CDN over HTTP.        */
/* ------------------------------------------------------------------ */

function safeJoin(root: string, ...parts: string[]): string | null {
  const full = path.join(root, ...parts)
  const normRoot = path.resolve(root) + path.sep
  if (!path.resolve(full).startsWith(normRoot.slice(0, -1))) return null
  return full
}

/**
 * Read a template file (html, css, js, etc.) and return contents as a UTF-8
 * string. Tries the local filesystem first (build, dev, and any function
 * where the templates happen to be traced); falls back to fetching the
 * matching `/_templates/...` static asset over HTTP for production SSR
 * functions where the templates are intentionally excluded from the bundle.
 */
export async function readTemplateFile(
  nicheSlug: string,
  templateSlug: string,
  filePath: string,
): Promise<string | null> {
  const template = getTemplate(nicheSlug, templateSlug)
  if (!template) return null

  const fsRoot = getFsRoot()
  if (fsRoot) {
    const fullPath = safeJoin(fsRoot, template.dir, filePath)
    if (fullPath) {
      try {
        if (fs.existsSync(fullPath)) {
          return fs.readFileSync(fullPath, 'utf-8')
        }
      } catch { /* fall through to fetch */ }
    }
  }

  try {
    const url = `${templateBaseUrl()}/_templates/${template.dir}/${filePath}`
    const res = await fetch(url)
    if (!res.ok) return null
    return await res.text()
  } catch {
    return null
  }
}

/**
 * Read a template asset as raw bytes. Same fs-first / fetch-fallback shape
 * as readTemplateFile, used by the asset proxy route for binary content
 * (images, fonts).
 */
export async function readTemplateFileBuffer(
  nicheSlug: string,
  templateSlug: string,
  filePath: string,
): Promise<Buffer | null> {
  const template = getTemplate(nicheSlug, templateSlug)
  if (!template) return null

  const fsRoot = getFsRoot()
  if (fsRoot) {
    const fullPath = safeJoin(fsRoot, template.dir, filePath)
    if (fullPath) {
      try {
        if (fs.existsSync(fullPath)) {
          return fs.readFileSync(fullPath)
        }
      } catch { /* fall through to fetch */ }
    }
  }

  try {
    const url = `${templateBaseUrl()}/_templates/${template.dir}/${filePath}`
    const res = await fetch(url)
    if (!res.ok) return null
    const arr = await res.arrayBuffer()
    return Buffer.from(arr)
  } catch {
    return null
  }
}

/** Replace all {{PLACEHOLDER}} tokens with provided values */
export function hydrateTemplate(html: string, values: Record<string, string>): string {
  let result = html
  for (const [key, value] of Object.entries(values)) {
    const regex = new RegExp(`\\{\\{${key}\\}\\}`, 'g')
    result = result.replace(regex, value)
  }
  result = result.replace(/\{\{[A-Z_]+\}\}/g, '')
  return result
}
